version: '1.0'
stages:

steps:
  run_terragrunt_test:
    title: Run Terragrunt Test
    image: dfdsdk/terratest-runner:0.11
    commands:
      - export GOPATH="./codefresh"
      - cd ./test
      - pwd
      - dep ensure
      - go test -v -run TestTerraformBasicExample